require:
  - rubocop-rspec

AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 2.3

inherit_from:
  - ./rubocop/gemspec.yml
  - ./rubocop/layout.yml
  - ./rubocop/lint.yml
  - ./rubocop/metrics.yml
  - ./rubocop/naming.yml
  - ./rubocop/performance.yml
  - ./rubocop/security.yml
  - ./rubocop/style.yml
  - ./rubocop/rspec/rspec.yml
