sudo: false
language: ruby
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - ruby-head
before_install: gem install bundler -v 1.15.4
script:
  - bundle exec rubocop
  - bundle exec rspec
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
